#!/bin/bash

# sjekk om jo er installert:

if ! which jo > /dev/null; then
echo "You need to have jo installed. Installing now"
sudo apt-get install -y jo
sleep 5s
fi

# hvilken URL som skal brukes. tilpass dette:
URL="http://admin:kult@192.168.131.156:5984/clog"

# lag JSON
JSON=$( jo message="$1" date="$(date)" host=$HOSTNAME )

# send til databasen
curl -H "Content-Type: application/json" -X POST -d "$JSON" $URL