#!/bin/bash
ipAddresse=$(hostname -I | awk '{print $1}')
MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')

until [[ "${MountedVolumes}" == *"/bf_config"* ]]; do
        echo $MountedVolumes
	sudo mount -t glusterfs $ipAddresse:bf_config /bf_config
	sleep 2s
        MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')
done

until [[ "${MountedVolumes}" == *"/bf_images"* ]]; do
        echo $MountedVolumes
        sudo mount -t glusterfs $ipAddresse:bf_images /bf_images
        sleep 2s
        MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')
done



url="https://discordapp.com/api/webhooks/830039049229959168/PI9T3bDge_zrEYXf7IHt7DBMepcAZ2pBWRPkPGtqLiWOGzzMHvoQ_Zz97aJsjfDiNfSo"
curl -H "Content-Type: application/json" -X POST -d '{"content":"'"$HOSTNAME: Volum er mountet"'"}'  $url
