#!/bin/bash
ipAddresse=$(hostname -I | awk '{print $1}')
MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')
#echo $ipAddresse
#until [[ "${MountedVolumes}" == "/bf_config /bf_images " ]]; 
#do
#	sudo mount -t glusterfs $ipAddresse:bf_config /bf_config
#	sudo mount -t glusterfs $ipAddresse:bf_images /bf_images
#	sleep 5s
	MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')
#done

#if [[ "${MountedVolumes}" == *"/bf_config"* ]]
#then
#	echo "De er like config "
#else
#	echo "De er ikke loke config"
#fi

until [[ "${MountedVolumes}" == *"/bf_config"* ]]; do
        echo $MountedVolumes
	sudo mount -t glusterfs $ipAddresse:bf_config /bf_config
	sleep 2s
        MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')
done

until [[ "${MountedVolumes}" == *"/bf_images"* ]]; do
        echo $MountedVolumes
        sudo mount -t glusterfs $ipAddresse:bf_images /bf_images
        sleep 2s
        MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')
done

FILE=/usr/local/bin/alertDiscord
if test -f "$FILE"; then
    alertDiscord volum er mounter paa "$HOSTNAME"
fi
