#!/bin/bash
#Loop until the 2 volumes are mounted. Must be done before we can proceed.
MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')

until [[ "${MountedVolumes}" == *"/bf_config"* ]]; do
        echo $MountedVolumes
        sleep 2s
        MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')
done

until [[ "${MountedVolumes}" == *"/bf_images"* ]]; do
        echo $MountedVolumes
        sleep 2s
        MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')
done


#Hent serverens ip-addresse
ipAddresse=$(hostname -I | awk '{print $1}')

#Restart the database server
sudo cockroach start --insecure\
	 --store=/bfdata --listen-addr=0.0.0.0:26257\
	 --http-addr=0.0.0.0:8080 --background\
	 --join=192.168.131.156:26257,192.168.131.220:26257,192.168.129.73:26257\
	 --advertise-addr="${ipAddresse}":26257 --max-offset=1500ms

url="https://discordapp.com/api/webhooks/830039049229959168/PI9T3bDge_zrEYXf7IHt7DBMepcAZ2pBWRPkPGtqLiWOGzzMHvoQ_Zz97aJsjfDiNfSo"
curl -H "Content-Type: application/json" -X POST -d '{"content":"'"$HOSTNAME: Startet Cockroachdb"'"}'  $url

