#!/bin/bash

finnesDatabase=$(curl http://localhost:8080/health)
finnesConfig=false
SUB='{'
MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')


while ! $finnesConfig;
do
if [[ $finnesDatabase == "$SUB"* ]];
then
	until [[ "${MountedVolumes}" == *"/bf_config"* ]]; do
        sleep 2s
        MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')
	done

	until [[ "${MountedVolumes}" == *"/bf_images"* ]]; do
        sleep 2s
        MountedVolumes=$(df -h | awk '{print $6}'| grep '/bf_*' | tr '\n' ' ')
	done

	sudo systemctl start docker
	finnesConfig=true
else
	finnesDatabase=$(curl http://localhost:8080/health)
	sleep 5s
fi
done

url="https://discordapp.com/api/webhooks/830039049229959168/PI9T3bDge_zrEYXf7IHt7DBMepcAZ2pBWRPkPGtqLiWOGzzMHvoQ_Zz97aJsjfDiNfSo"
curl -H "Content-Type: application/json" -X POST -d '{"content":"'"$HOSTNAME: Startet Docker"'"}'  $url
