#!/bin/bash
source /home/ubuntu/robusteTjenester/manager/DCSG2003_V21_group13-openrc.sh

ShutOff=$(openstack server list | grep "SHUTOFF" | awk '{print $4}')

#echo "Her er ShutOff: $ShutOff"

navnPaServer=$(echo "$ShutOff" | tr '\n' ' ')

echo "Her er navnPaServer: $navnPaServer"

if [[ $navnPaServer == *"server"* ]]
then
        echo "navnPaServer inneholdt $navnPaServer"
        openstack server start $navnPaServer
	url="https://discordapp.com/api/webhooks/830039049229959168/PI9T3bDge_zrEYXf7IHt7DBMepcAZ2pBWRPkPGtqLiWOGzzMHvoQ_Zz97aJsjfDiNfSo"
	curl -H "Content-Type: application/json" -X POST -d '{"content":"'"$HOSTNAME: Restartet maskinen $navnPaServer"'"}'  $url

else
        echo "Den er tom: $Variabel2"
fi
