#!/bin/bash


#Velg floating Ip til den nye maskinen
printf "Vil du ha en floating IP-addresse på maskinen (y/n): "
read hentIp

if [ -z "$hentIp" ]
then
	printf "\nSkriv noe neste gang\n"
	exit 1;
else
	if [ "$hentIp" == "y" ]
	then
		if openstack floating ip list | grep "None" > /dev/null
		then
			printf "\nDet fantes floating ip\n"
			openstack floating ip list | grep "None" | awk '{print $4, "   -->   "$2}'
			printf "\nCopy paste ID til floating IP du vil ha pAa ny maskin: "
			read valgtIp
			printf "\nDu har valgt floating IP-addresse: $valgtIp\n"
		else
			printf "\nDet fantes ikke floating ip\n"
			#exit 0;
		fi	
	else
		printf "\nDu har valgt Aa ikke knytte floating IP-addresse til ny maskin\n"
	fi	

fi
